// Generated by CoffeeScript 1.9.0
var Id, crypto;

crypto = require('crypto');

Id = (function() {
  function Id(_at_allowedChars, _at_length) {
    var err, i, length, rnd, _i, _ref;
    this.allowedChars = _at_allowedChars != null ? _at_allowedChars : 'ABCDEFGHIJKLMNOPQRSTUVXYZ';
    this.length = _at_length != null ? _at_length : 4;
    try {
      rnd = crypto.randomBytes(this.length);
      this.value = new Array(this.length);
      length = this.allowedChars.length;
      for (i = _i = 0, _ref = this.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.value[i] = this.allowedChars[rnd[i] % length];
      }
      this.value = this.value.join('');
    } catch (_error) {
      err = _error;
      console.error(err);
    }
  }

  Id.prototype.toString = function() {
    return this.value;
  };

  Id.prototype.valueOf = function() {
    return this.value;
  };

  return Id;

})();

module.exports = Id;
